// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreToolReverseEngineeringTest.Models;

public partial class School
{
    public int Id { get; set; }

    public string Name { get; set; }

    public short? RegionNumber { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string Phone { get; set; }

    public string Membership1 { get; set; }

    public string Membership1seen { get; set; }

    public string Membership2 { get; set; }

    public string Membership2seen { get; set; }

    public string Membership3 { get; set; }

    public string Membership3seen { get; set; }

    public string Membership4 { get; set; }

    public string Membership4seen { get; set; }

    public string CoordNew { get; set; }

    public string CoordFirstName { get; set; }

    public string CoordLastName { get; set; }

    public string CoordAddress { get; set; }

    public string CoordCity { get; set; }

    public string CoordState { get; set; }

    public string CoordPostalCode { get; set; }

    public string CoordPhone { get; set; }

    public string CoordAltPhone { get; set; }

    public string CoordMobilePhone { get; set; }

    public string CoordFaxNumber { get; set; }

    public string CoordEmailName { get; set; }

    public string Share { get; set; }

    public string Notes { get; set; }
}