CREATE TABLE [dbo].[Events](
	[ID] [int] NOT NULL,
	[EventName] [nvarchar](200) NULL,
	[LocationURL] [nvarchar](200) NULL,
	[LocationURLColor] [nvarchar](100) NULL,
	[LocationAddress] [nvarchar](100) NULL,
	[LocationCity] [nvarchar](30) NULL,
	[LocationState] [nvarchar](5) NULL,
	[LocationPhone] [nvarchar](50) NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[Location] [nvarchar](100) NULL,
	[Time] [nvarchar](100) NULL,
	[EventCoordinatorName] [nvarchar](100) NULL,
	[EventCoordinatorEmail] [nvarchar](100) NULL,
	[EventCoordinatorPhone] [nvarchar](100) NULL,
	[InformationURL] [nvarchar](100) NULL,
	[LocationMapURL] [nvarchar](100) NULL,
	[EventPayeeName] [nvarchar](100) NULL,
	[EventPayeeAddress1] [nvarchar](100) NULL,
	[EventPayeeAddress2] [nvarchar](100) NULL,
	[EventPayeeCity] [nvarchar](50) NULL,
	[EventPayeeState] [nvarchar](30) NULL,
	[EventPayeeZipCode] [nvarchar](15) NULL,
	[EventPayeePhone1] [nvarchar](20) NULL,
	[EventPayeeEmail1] [nvarchar](100) NULL,
	[EventCost] [nvarchar](20) NULL,
	[LateEventCost] [nvarchar](20) NULL,
	[LateEventCostStartDate] [date] NULL,
	[PaymentDueDate] [date] NULL,
	[EventMakeChecksOutTo] [nvarchar](150) NULL,
	[EventVolunteerInformationMessage] [nvarchar](max) NULL,
	[TeamsVolunteerWantsToSeeMessage] [nvarchar](max) NULL,
	[EventMailBody] [nvarchar](max) NULL,
 CONSTRAINT [PK_events] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]