CREATE TABLE [dbo].[TournamentRegistration](
	[TeamID] [int] IDENTITY(1,1) NOT NULL,
	[MembershipName] [nvarchar](50) NULL,
	[MembershipNumber] [nvarchar](50) NULL,
	[ProblemID] [int] NULL,
	[Division] [nvarchar](50) NULL,
	[SchoolID] [int] NULL,
	[CoachFirstName] [nvarchar](50) NULL,
	[CoachLastName] [nvarchar](50) NULL,
	[CoachAddress] [nvarchar](255) NULL,
	[CoachCity] [nvarchar](50) NULL,
	[CoachState] [nvarchar](20) NULL,
	[CoachZipCode] [nvarchar](20) NULL,
	[CoachEveningPhone] [nvarchar](30) NULL,
	[CoachDaytimePhone] [nvarchar](30) NULL,
	[CoachMobilePhone] [nvarchar](30) NULL,
	[CoachEmailAddress] [nvarchar](50) NULL,
	[AltCoachFirstName] [nvarchar](50) NULL,
	[AltCoachLastName] [nvarchar](50) NULL,
	[AltCoachEveningPhone] [nvarchar](50) NULL,
	[AltCoachDaytimePhone] [nvarchar](50) NULL,
	[AltCoachMobilePhone] [nvarchar](30) NULL,
	[AltCoachEmailAddress] [nvarchar](50) NULL,
	[MemberFirstName1] [nvarchar](50) NULL,
	[MemberLastName1] [nvarchar](50) NULL,
	[MemberGrade1] [nvarchar](50) NULL,
	[MemberFirstName2] [nvarchar](50) NULL,
	[MemberLastName2] [nvarchar](50) NULL,
	[MemberGrade2] [nvarchar](50) NULL,
	[MemberFirstName3] [nvarchar](50) NULL,
	[MemberLastName3] [nvarchar](50) NULL,
	[MemberGrade3] [nvarchar](50) NULL,
	[MemberFirstName4] [nvarchar](50) NULL,
	[MemberLastName4] [nvarchar](50) NULL,
	[MemberGrade4] [nvarchar](50) NULL,
	[MemberFirstName5] [nvarchar](50) NULL,
	[MemberLastName5] [nvarchar](50) NULL,
	[MemberGrade5] [nvarchar](50) NULL,
	[MemberFirstName6] [nvarchar](50) NULL,
	[MemberLastName6] [nvarchar](50) NULL,
	[MemberGrade6] [nvarchar](50) NULL,
	[MemberFirstName7] [nvarchar](50) NULL,
	[MemberLastName7] [nvarchar](50) NULL,
	[MemberGrade7] [nvarchar](50) NULL,
	[Spontaneous] [bit] NULL,
	[Notes] [nvarchar](max) NULL,
	[SpecialConsiderations] [nvarchar](max) NULL,
	[SchedulingIssues] [nvarchar](max) NULL,
	[Paid] [smallint] NULL,
	[JudgeID] [smallint] NULL,
	[TeamRegistrationFee] [nvarchar](20) NULL,
	[VolunteerID] [int] NULL,
	[TimeRegistrationStarted] [datetime] NULL,
	[TimeRegistered] [datetime] NULL,
	[UserAgent] [nvarchar](max) NULL,
 CONSTRAINT [PK_TournamentRegistration] PRIMARY KEY CLUSTERED 
(
	[TeamID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]