// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OdysseyCoreMvc.Models
{
    public partial class CoachesTrainingRoles
    {
        public byte Id { get; set; }
        public string Name { get; set; }
    }
}