// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OdysseyCoreMvc.Models
{
    public partial class ContactUsRecipients
    {
        public byte Id { get; set; }
        public string ContactName { get; set; }
        public string EmailAddress { get; set; }
    }
}