//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdysseyCoreMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Membership_1 { get; set; }
        public string Membership_1seen { get; set; }
        public string Membership_2 { get; set; }
        public string Membership_2seen { get; set; }
        public string Membership_3 { get; set; }
        public string Membership_3seen { get; set; }
        public string Membership_4 { get; set; }
        public string Membership_4seen { get; set; }
        public string CoordNew_ { get; set; }
        public string CoordFirstName { get; set; }
        public string CoordLastName { get; set; }
        public string CoordAddress { get; set; }
        public string CoordCity { get; set; }
        public string CoordState { get; set; }
        public string CoordPostalCode { get; set; }
        public string CoordPhone { get; set; }
        public string CoordAltPhone { get; set; }
        public string CoordMobilePhone { get; set; }
        public string CoordFaxNumber { get; set; }
        public string CoordEmailName { get; set; }
        public string Share_ { get; set; }
        public string Notes { get; set; }
    }
}
