//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdysseyCoreMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int VolunteerID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DaytimePhone { get; set; }
        public string EveningPhone { get; set; }
        public string MobilePhone { get; set; }
        public string EmailAddress { get; set; }
        public string Notes { get; set; }
        public string VolunteerWantsToSee { get; set; }
        public Nullable<System.DateTime> TimeRegistrationStarted { get; set; }
        public Nullable<System.DateTime> TimeRegistered { get; set; }
        public Nullable<System.DateTime> TimeAssignedToTeam { get; set; }
        public string UserAgent { get; set; }
    }
}
