// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JudgeRegistrationRazor.Models;

public partial class Volunteer
{
    public int Id { get; set; }

    public int? TeamId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string DaytimePhone { get; set; }

    public string EveningPhone { get; set; }

    public string MobilePhone { get; set; }

    public string EmailAddress { get; set; }

    public string Notes { get; set; }

    public string VolunteerWantsToSee { get; set; }

    public DateTime? TimeRegistrationStarted { get; set; }

    public DateTime? TimeRegistered { get; set; }

    public DateTime? TimeAssignedToTeam { get; set; }

    public string UserAgent { get; set; }
}