CREATE TABLE [dbo].[Judges](
	[JudgeID] [int] IDENTITY(1,1) NOT NULL,
	[TeamID] [nvarchar](50) NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Address] [nvarchar](255) NULL,
	[AddressLine2] [nvarchar](255) NULL,
	[City] [nvarchar](50) NULL,
	[State] [nvarchar](20) NULL,
	[ZipCode] [nvarchar](20) NULL,
	[DaytimePhone] [nvarchar](30) NULL,
	[EveningPhone] [nvarchar](30) NULL,
	[MobilePhone] [nvarchar](30) NULL,
	[EmailAddress] [nvarchar](50) NULL,
	[Notes] [nvarchar](max) NULL,
	[ProblemChoice1] [nvarchar](60) NULL,
	[ProblemChoice2] [nvarchar](60) NULL,
	[ProblemChoice3] [nvarchar](60) NULL,
	[HasChildrenCompeting] [nvarchar](3) NULL,
	[COI] [nvarchar](50) NULL,
	[ProblemCOI1] [nvarchar](60) NULL,
	[ProblemCOI2] [nvarchar](60) NULL,
	[ProblemCOI3] [nvarchar](60) NULL,
	[ProblemAssigned] [nvarchar](50) NULL,
	[InformationMailed?] [bit] NULL,
	[AttendedJT?] [bit] NULL,
	[Active] [bit] NULL,
	[WillingToBeScorechecker] [nvarchar](3) NULL,
	[TshirtSize] [nvarchar](50) NULL,
	[WantsCEUCredit] [nvarchar](3) NULL,
	[YearsOfLongTermJudgingExperience] [nvarchar](50) NULL,
	[YearsOfSpontaneousJudgingExperience] [nvarchar](50) NULL,
	[PreviousPositions] [nvarchar](100) NULL,
	[ProblemID] [nvarchar](50) NULL,
	[TimeRegistered] [datetime] NULL,
	[TimeAssignedToTeam] [datetime] NULL,
	[TimeRegistrationStarted] [datetime] NULL,
	[UserAgent] [nvarchar](max) NULL,
 CONSTRAINT [PK_judges] PRIMARY KEY CLUSTERED 
(
	[JudgeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]