// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreToolReverseEngineeringTest.Models;

public partial class ContactUsRecipient
{
    public byte Id { get; set; }

    public string ContactName { get; set; }

    public string EmailAddress { get; set; }
}