// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreToolReverseEngineeringTest.Models;

public partial class Judge
{
    public int Id { get; set; }

    public string TeamId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public string DaytimePhone { get; set; }

    public string EveningPhone { get; set; }

    public string MobilePhone { get; set; }

    public string EmailAddress { get; set; }

    public string Notes { get; set; }

    public string ProblemChoice1 { get; set; }

    public string ProblemChoice2 { get; set; }

    public string ProblemChoice3 { get; set; }

    public string HasChildrenCompeting { get; set; }

    public string Coi { get; set; }

    public string ProblemCoi1 { get; set; }

    public string ProblemCoi2 { get; set; }

    public string ProblemCoi3 { get; set; }

    public string ProblemAssigned { get; set; }

    public bool? InformationMailed { get; set; }

    public bool? AttendedJt { get; set; }

    public bool? Active { get; set; }

    public string WillingToBeScorechecker { get; set; }

    public string TshirtSize { get; set; }

    public string WantsCeucredit { get; set; }

    public string YearsOfLongTermJudgingExperience { get; set; }

    public string YearsOfSpontaneousJudgingExperience { get; set; }

    public string PreviousPositions { get; set; }

    public string ProblemId { get; set; }

    public DateTime? TimeRegistered { get; set; }

    public DateTime? TimeAssignedToTeam { get; set; }

    public DateTime? TimeRegistrationStarted { get; set; }

    public string UserAgent { get; set; }
}