// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreToolReverseEngineeringTest.Models;

public partial class Problem
{
    public int Id { get; set; }

    public string ProblemCategory { get; set; }

    public string ProblemName { get; set; }

    public string ProblemDescription { get; set; }

    public string Divisions { get; set; }

    public string CostLimit { get; set; }

    public string ProblemCaptainId { get; set; }

    public string PcfirstName { get; set; }

    public string PclastName { get; set; }

    public string Pcaddress { get; set; }

    public string Pccity { get; set; }

    public string PcstateOrProvince { get; set; }

    public string PcpostalCode { get; set; }

    public string PcworkPhone { get; set; }

    public string PchomePhone { get; set; }

    public string PcmobilePhone { get; set; }

    public string PcfaxNumber { get; set; }

    public string Pcemail1 { get; set; }

    public string Pcemail2 { get; set; }

    public string Notes { get; set; }
}