//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdysseyMvc4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Judge
    {
        public int JudgeID { get; set; }
        public string TeamID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string DaytimePhone { get; set; }
        public string EveningPhone { get; set; }
        public string MobilePhone { get; set; }
        public string EmailAddress { get; set; }
        public string Notes { get; set; }
        public string COI { get; set; }
        public string ProblemCOI1 { get; set; }
        public string ProblemCOI2 { get; set; }
        public string ProblemCOI3 { get; set; }
        public string ProblemChoice1 { get; set; }
        public string ProblemChoice2 { get; set; }
        public string ProblemChoice3 { get; set; }
        public string ProblemAssigned { get; set; }
        public Nullable<bool> InformationMailed_ { get; set; }
        public Nullable<bool> AttendedJT_ { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TshirtSize { get; set; }
        public string CEU { get; set; }
        public string YearsExperience { get; set; }
        public string PreviousPositions { get; set; }
        public string ProblemID { get; set; }
        public Nullable<System.DateTime> TimeRegistered { get; set; }
        public Nullable<System.DateTime> TimeAssignedToTeam { get; set; }
        public Nullable<System.DateTime> TimeRegistrationStarted { get; set; }
        public string UserAgent { get; set; }
    }
}
