//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdysseyMvc4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int VolunteerID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string VolunteerFirstName { get; set; }
        public string VolunteerLastName { get; set; }
        public string VolunteerDaytimePhone { get; set; }
        public string VolunteerEveningPhone { get; set; }
        public string VolunteerMobilePhone { get; set; }
        public string VolunteerEmail { get; set; }
        public string VolunteerNotes { get; set; }
        public string VolunteerWantsToSee { get; set; }
        public Nullable<System.DateTime> TimeRegistrationStarted { get; set; }
        public Nullable<System.DateTime> TimeRegistered { get; set; }
        public Nullable<System.DateTime> TimeAssignedToTeam { get; set; }
        public string UserAgent { get; set; }
    }
}
