// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OdysseyCoreMvc.Models
{
    public partial class CoachesTrainingRegistrations
    {
        public int RegistrationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SchoolName { get; set; }
        public string Role { get; set; }
        public string Division { get; set; }
        public string SelectedProblem { get; set; }
        public string EmailAddress { get; set; }
        public string YearsInvolved { get; set; }
        public string RegionNumber { get; set; }
        public DateTime? TimeRegistered { get; set; }
        public string UserAgent { get; set; }
    }
}