// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdysseyMvc2024.Models;

#nullable disable

namespace OdysseyMvc2024.Migrations
{
    [DbContext(typeof(OdysseyEntities))]
    [Migration("20241005151813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdysseyMvc2024.Models.Config", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Config", (string)null);
                });

            modelBuilder.Entity("OdysseyMvc2024.Models.ContactUsRecipient", b =>
                {
                    b.Property<byte>("ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("contact_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_address")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContactUsRecipient", (string)null);
                });

            modelBuilder.Entity("OdysseyMvc2024.Models.ContactUsSenderRole", b =>
                {
                    b.Property<byte>("ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("role_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContactUsSenderRole", (string)null);
                });

            modelBuilder.Entity("OdysseyMvc2024.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventCoordinatorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventCoordinatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventCoordinatorPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventMailBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventMakeChecksOutTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeeAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeeAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeeCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeeEmail1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeePhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeeState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPayeeZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventVolunteerInformationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformationURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LateEventCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LateEventCostStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationMapURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationURLColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamsVolunteerWantsToSeeMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("OdysseyMvc2024.Models.Judge", b =>
                {
                    b.Property<int>("JudgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JudgeID"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AttendedJT_")
                        .HasColumnType("bit");

                    b.Property<string>("COI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaytimePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EveningPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasChildrenCompeting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("InformationMailed_")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPositions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemAssigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemCOI1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemCOI2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemCOI3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemChoice1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemChoice2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemChoice3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeAssignedToTeam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeRegistered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeRegistrationStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("TshirtSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WantsCEUCredit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WillingToBeScorechecker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsOfLongTermJudgingExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsOfSpontaneousJudgingExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JudgeID");

                    b.ToTable("Judge", (string)null);
                });

            modelBuilder.Entity("OdysseyMvc2024.Models.Problem", b =>
                {
                    b.Property<int>("ProblemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemID"));

                    b.Property<string>("CostLimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Divisions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCEmail1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCEmail2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCFaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCHomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCMobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCStateOrProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCWorkPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemCaptainID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProblemID");

                    b.ToTable("Problem", (string)null);
                });

            modelBuilder.Entity("OdysseyMvc2024.Models.School", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordAltPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordEmailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordFaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordMobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordNew_")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_1seen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_2seen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_3seen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membership_4seen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Share_")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("School", (string)null);
                });

            modelBuilder.Entity("OdysseyMvc2024.Models.TournamentRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltCoachDaytimePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltCoachEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltCoachEveningPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltCoachFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltCoachLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltCoachMobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachDaytimePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachEveningPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachMobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("JudgeID")
                        .HasColumnType("smallint");

                    b.Property<string>("MemberFirstName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGrade1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGrade2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGrade3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGrade4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGrade5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGrade6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGrade7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberLastName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberLastName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberLastName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberLastName4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberLastName5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberLastName6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberLastName7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Paid")
                        .HasColumnType("smallint");

                    b.Property<int?>("ProblemID")
                        .HasColumnType("int");

                    b.Property<string>("SchedulingIssues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolID")
                        .HasColumnType("int");

                    b.Property<string>("SpecialConsiderations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Spontaneous")
                        .HasColumnType("bit");

                    b.Property<string>("TeamRegistrationFee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeRegistered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeRegistrationStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VolunteerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TournamentRegistration", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
