//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;

namespace OdysseyMvc2024.Models
{
    public interface IOdysseyEntities
    {
        DbSet<Config> Configs { get; set; }
        DbSet<ContactUsRecipient> ContactUsRecipients { get; set; }
        DbSet<ContactUsSenderRole> ContactUsSenderRoles { get; set; }
        DbSet<Event> Events { get; set; }
        DbSet<Judge> Judges { get; set; }
        DbSet<Problem> Problems { get; set; }
        DbSet<School> Schools { get; set; }
        DbSet<TournamentRegistration> TournamentRegistrations { get; set; }
    }
}